bert: bert-base-cased
distil: distilbert-base-cased
albert: albert-base-v2
roberta: roberta-base

input_dim: 10000
output_dim: 10000

emb_dim: 768
hidden_dim: 768

pff_dim: 1536

n_layers: 3
n_heads: 8
dropout_ratio: 0.1

pad_idx: 0
max_len: 100